### ISSUE TITLE
レシピ登録ボタンをもっと目立たせて欲しい

### ISSUE THREAD

**Issue by s12bt** [aquariumyossy/omoide-recipe#2]
![image](https://user-images.githubusercontent.com/680192/88765619-b556c280-d1b1-11ea-90b0-cf0b02176497.png)
どこを押せばこの画面を抜けられるのか迷ってしまったので、もっと目立たせて欲しい

**Comment by aquariumyossy** [comment]
見直してみるとsubmit系のボタンがアプリ全体でわかりにくかもしれません。全体のCSSや配置を見直します。

**Comment by aquariumyossy** [comment]
![image](https://user-images.githubusercontent.com/61150000/88872435-1be0ec80-d255-11ea-93f9-86a30ba9b96e.png)
こんな感じで左寄せにして文字サイズを大きくして見ましたがいかがでしょう？
レシピ編集画面も同じように変更しました。

**Comment by s12bt** [comment]
![image](https://user-images.githubusercontent.com/680192/88875381-20f56a00-d25c-11ea-8554-bcb32c3df990.png)


見出しの色と同じだから、左寄せだとますます見出し感強まってしまったかもしれないですね。
セオリー通りなボタン(背景色をひく、枠で囲む)にしたほうがいいかもしれないです。そしてもっと思い切って大きくしても良さそう。

ボタンのデザインのパターンは、UIフレームワークをよく参考にします。
twitter bootstrap button https://getbootstrap.com/docs/4.5/components/buttons/
bluma https://bulma.io/documentation/elements/button/

**Comment by aquariumyossy** [comment]
こちらもこんな感じにして見ました。レシピ編集画面や他の画面なんかも共通の背景色・文字色で統一してみました。
![image](https://user-images.githubusercontent.com/61150000/88993553-439d8680-d321-11ea-978f-046b426e2754.png)
