### ISSUE TITLE
ログインボタンを見失ってしまう

### ISSUE THREAD

**Issue by s12bt** [aquariumyossy/omoide-recipe#4]
![image](https://user-images.githubusercontent.com/680192/88766052-5b0a3180-d1b2-11ea-9751-fd2d679326af.png)

アイコンが付いている「新規ユーザー登録」のほうに目がいきがち

**Comment by aquariumyossy** [comment]
ありがとうございます。作成過程で見慣れてしまいましたがそのとおりですね。
アイコンを付けたりもうちょっとわかりやすくしてみます。
新規ユーザー登録以下をもう少しスペースあけて配置することも検討します。

**Comment by aquariumyossy** [comment]
https://omoide-recipe.jp/users/sign_in

ログイン画面を修正してみました。すこしわかりやすくなったでしょうか。
新規ユーザー登録はヘッダーにもあるので削除してみました。

と思ったんですが修正したCSSが反映されない・・・
https://qiita.com/fukaya_dea/items/456ac841ce34f05023a9
このあたり参考にしながら調整してみます。
→　出張中の電車のなかで解決しました。railsのproduction環境ではstylesheetなどのassetsをprecomplileする仕様になっていまして、scssファイルを差し替えるだけだとcssが反映されない状態だったので、あらためてprecomplileを実施してapacheを再起動したら無事反映されました。

**Comment by s12bt** [comment]
何が目立って何が目立ってないのかを調べるのに、アクセシビリティ系のツールにかけるとよいことがあります
Chromeのdevelopper toolのChromeLensを使います
https://www.moongift.jp/2016/08/chromelens-google-chrome%E6%A9%9F%E8%83%BD%E6%8B%A1%E5%BC%B5%E3%81%AEweb%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B7%E3%83%93%E3%83%AA%E3%83%86%E3%82%A3%E3%83%81%E3%82%A7%E3%83%83%E3%82%AB%E3%83%BC/

![image](https://user-images.githubusercontent.com/680192/88873188-15537480-d257-11ea-9f74-d365c76b3227.png)
![image](https://user-images.githubusercontent.com/680192/88873336-69f6ef80-d257-11ea-8905-37516b834d7a.png)

こうして見てみると、一番目立って見えるのは「ログイン」のタイトルで、ログインボタンは気持ちちょっと目立つかなくらいの気もします。

ログインのタイトルのように
- 背景に色をつける
- 文字を中央揃えにして、他の要素と同じものではないことを表現する

ともっと差異がでてよいかと思います！

**Comment by aquariumyossy** [comment]
ありがとうございます。こんな感じで中央ぞろえ・背景変更・押し込みボタンにしてみましたがいかがでしょう？
背景色・文字色の組み合わせけっこうむずかしい。
![image](https://user-images.githubusercontent.com/61150000/88993468-020cdb80-d321-11ea-94d5-978c290412bb.png)
