### ISSUE TITLE
適量　が欲しい！

### ISSUE THREAD

**Issue by cottontonton** [aquariumyossy/omoide-recipe#6]

**Comment by cottontonton** [comment]
ひとつまみ　とかね！

**Comment by s12bt** [comment]
少々とか！

**Comment by s12bt** [comment]
塩コショウは少々ってつけること多い気がして
塩コショウが入力されたら、少々ってサジェストされてもうれしいかも

**Comment by aquariumyossy** [comment]
了解です！
その点、この前ワタムからアドバイスもらったので、材料＞量のカラムのvalidationをallo_blank:trueにしたので、量を空欄にして単位のところに「適量」を記入できるようになりました。
「適量」「少々」とかをドロップダウンリストとかで選べるようにするところからはじめます！

**Comment by aquariumyossy** [comment]
とりあえず、プルダウンリストで選択できるようにして見ました！
https://omoide-recipe.jp
